<?php
/************************************************************
 * *
 *  * Copyright © Boolfly. All rights reserved.
 *  * See COPYING.txt for license details.
 *  *
 *  * @author    info@boolfly.com
 * *  @project   Megamenu
 */
?>
<ul class="bf-megamenu menu-hover bf-vertical-left">
    <?php foreach ($block->getMenuTree() as $item):?>
        <li id="boolfly-menu-item-<?= /* @escapeNotVerified */ $item['record_id'];?>"
            class="menu-item level-top menu-dropdown nav-0">
            <?= $block->getChildContentHtml($item);?>
        </li>
    <?php endforeach;?>
</ul>
