<?php
/************************************************************
 * *
 *  * Copyright © Boolfly. All rights reserved.
 *  * See COPYING.txt for license details.
 *  *
 *  * @author    info@boolfly.com
 * *  @project   Megamenu
 */
/** @var \Boolfly\Megamenu\Block\Html\Menu $block */
?>
<ul class="boolfly-megamenu menu-hover <?= /* @escapeNotVerified */ $block->getMenuTemplate();?>">
    <?php foreach ($block->getMenuTree() as $item) :?>
        <li id="boolfly-menu-item-<?= /* @escapeNotVerified */ $item['record_id'];?>"
            class="menu-item level-top menu-dropdown nav-0 <?= /* @escapeNotVerified */ $block->getAdditionalClasses($item);?>">
            <?= /* @escapeNotVerified */ $block->getChildContentHtml($item);?>
        </li>
    <?php endforeach;?>
</ul>
