<?php
/************************************************************
 * *
 *  * Copyright © Boolfly. All rights reserved.
 *  * See COPYING.txt for license details.
 *  *
 *  * @author    info@boolfly.com
 * *  @project   Megamenu
 */
?>
<ul>
    <?php foreach ($block->getMenuItems() as $item):?>
        <li class="menu-item">
            <?= $block->getChildContentHtml($item)?>
        </li>
    <?php endforeach;?>
</ul>
