<?php
/************************************************************
 * *
 *  * Copyright © Boolfly. All rights reserved.
 *  * See COPYING.txt for license details.
 *  *
 *  * @author    info@boolfly.com
 * *  @project   Megamenu
 */
/** @var \Boolfly\Megamenu\Block\Html\Item $block */
?>
<?php
$type = 'header';
?>
<?php if ($block->isEnableBlock($type) && ($html = $block->getWysiwygContent($type))):?>
    <div class="head-wrapper">
        <?= /* @escapeNotVerified */ $html;?>
    </div>
<?php endif;?>