<?php
/************************************************************
 * *
 *  * Copyright © Boolfly. All rights reserved.
 *  * See COPYING.txt for license details.
 *  *
 *  * @author    info@boolfly.com
 * *  @project   Megamenu
 */
/** @var \Boolfly\Megamenu\Block\Html\Item $block */
?>
<?php
$type = 'left_block';
?>
<?php if ($block->isEnableBlock($type) && ($html = $block->getWysiwygContent($type))):?>
    <div class="left-wrapper" style="<?= /* @escapeNotVerified */ $block->getWidthStyle($type)?>">
        <div class="bf-menu-content left">
            <?= /* @escapeNotVerified */ $html;?>
        </div>
    </div>
<?php endif;?>