<?php
/************************************************************
 * *
 *  * Copyright © Boolfly. All rights reserved.
 *  * See COPYING.txt for license details.
 *  *
 *  * @author    info@boolfly.com
 * *  @project   Megamenu
 */
?>
<?php
$type = 'right_block';
?>
<?php if ($block->isEnableBlock($type) && ($html = $block->getWysiwygContent($type))) :?>
    <div class="right-wrapper" style="<?= /* @escapeNotVerified */ $block->getWidthStyle($type)?>">
        <div class="bf-menu right-content">
            <?= /* @escapeNotVerified */ $html;?>
        </div>
    </div>
<?php endif;?>